[build]
  publish = "frontend/build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  # Use a modern Node version; compatible with Vite and functions
  NODE_VERSION = "18.20.3"
  NPM_FLAGS = "--legacy-peer-deps"
  # Install devDependencies during build so Vite is available
  NPM_CONFIG_PRODUCTION = "false"
  # Secrets scanning: omit known keys from scanning (values are set in UI, not committed)
  SECRETS_SCAN_OMIT_KEYS = "JWT_SECRET,MONGODB_URI,NODE_ENV,STRIPE_SECRET_KEY,PAYPAL_CLIENT_ID"

[dev]
  command = "npm start --prefix frontend"
  port = 8890
  targetPort = 3002
  publish = "frontend/build"
  functions = "netlify/functions"
  autoLaunch = false

# Redirect all API calls to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-:splat"
  status = 200
  force = true

# SPA routing - send all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force so existing static assets are served correctly
[[headers]]
  for = "/health.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/api/health"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/.netlify/functions/api-health"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"


# Headers for security and caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
